#
#  Makefile for  KISS-68030 & Mini-M68k  BIOS
#
#	make RETAIL=1		Option to make the public distribution
#	make MINI=1		Option to make MINI version explicitly
#	make KISS=1		Option to make KISS version explicitly
#  If RETAIL=1 is not specified, the DEBUG versions will be created
#
#  Total make of the distribution binaries:
#	make test
#	make MINI=1 RETAIL=1
#	make KISS=1 RETAIL=1	
#
BIOS_REVISION = 10.3b



ifndef MINI
BOARD = kiss
CPU = 68030
BIOSTEXT=0xFFF00000
BIOSDATA=0xFFFE4000
P=k
# room for 4Kb of data from 0xFFFE7400 to 0xFFFE7FFF
else
BOARD = mini
CPU = 68000
BIOSTEXT=0xFFF80000
BIOSDATA=0x0100
P=
# room for 3.75Kb of data from 0x0100 to 0x0FFF  (0x0F00 == 3840)
endif

TARGET = $(BOARD)$(BIOS_REVISION)

#  use 'make RETAIL=1' to remove all of the debugging code and
#  make the "retail" version of the BIOS
ifdef RETAIL
RETAIL = 1
ALL = stomp.h $(BOARD)-128.rom $(BOARD)-512.rom
BURN = $(BOARD)-128.rom
BIOSSIZE=48
#COPY = echo No save to microSD card
COPY =
else
RETAIL = 0
ALL = $(P)test128.bin $(P)test512.bin
BURN = $(P)test512.bin
BIOSSIZE = 64
#COPY = echo No save to microSD card
COPY =
endif
FLASH = SST39SF040
#FLASH = AM29F040B@dip32


ROM = ../cpm68e/rom
TOOLS = ../tools
EXE =

HEX2BIN = $(TOOLS)/hex2bin$(EXE)
BIN2HEX = $(TOOLS)/bin2hex$(EXE)

#
#
CDEFS = -DRETAIL=$(RETAIL) -DCPU=$(CPU)
ADEFS = --defsym RETAIL=$(RETAIL) --defsym CPU=$(CPU)

#------------------------------------------------------------------------
# GCC compilers are 4.1.1, 5.4.0, 9.0.0
#------------------------------------------------------------------------
ifndef GCC5
#---------------------------------------------------------
# make ELF output with GCC 4.1.1 cross-compiler

CROSSDIR = /usr/cross/m68k-elf
BIN = $(CROSSDIR)/bin
PREFIX = $(BIN)/m68k-elf-
#
CC = $(PREFIX)gcc
COPT = -Os -ansi -malign-int -nostdlib -m$(CPU) -Wall -Werror $(CDEFS)
AS = $(PREFIX)as
AOPT = -m$(CPU) -alhms $(ADEFS)
LD = $(PREFIX)ld
#LOPT = -Ttext $(BIOSTEXT) -Tdata $(BIOSDATA)
LOPT = --script rom-$(BOARD).ld
UOPT = -Ttext 0x1000 --entry begin
LIB = $(PREFIX)ar
LIBS = -L$(CROSSDIR)/m68k-elf/lib/m68000 -L$(CROSSDIR)/lib/gcc/m68k-elf/4.1.1/m68000 -lc -lgcc
OBJCOPY = $(PREFIX)objcopy
else
#----------------------------------------------------------
# make ELF output with GCC 5.x or GCC 9.x cross-compiler

CROSSDIR = /usr
BIN = $(CROSSDIR)/bin
PREFIX = $(BIN)/m68k-linux-gnu-
#
CC = $(PREFIX)gcc
COPT = -Os -ansi -malign-int -nostdlib -m$(CPU) -Wall $(CDEFS) # -fno-builtin
AS = $(PREFIX)as
AOPT = -m$(CPU) -alhms $(ADEFS)
LD = $(PREFIX)ld
LOPT = -Ttext $(BIOSTEXT) -Tdata $(BIOSDATA)
UOPT = -Ttext 0x1000 --entry begin
LIB = $(PREFIX)ar
#LIBS = -L$(CROSSDIR)/m68k-elf/lib/m68000 -L$(CROSSDIR)/lib/gcc/m68k-elf/4.1.1/m68000 -lc -lgcc
LIBS = -static -lc ../lib/68000.a
OBJCOPY = $(PREFIX)objcopy
endif
#------------------------------------------------------------------------


.SUFFIXES:   .c .s .o .out .hex .bin

.c.o:
	$(CC) -c $(COPT) $*.c
.s.o:
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s
.c.s:
	$(CC) -S $(COPT) $*.c

#.out.mod:
#	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
#		grep -v "set to" | sed "s/.text/     /" > $*.mod
#
#.out.sym:
#	grep "                " $*.map | grep -v "=" | grep -v "(" | \
#		grep -v LONG | grep -v "                 " | sort > $*.sym
#

SFILES = mfpic.s ppi.s allide.s siodef.s memtest.s ns202def.s biostrap.s \
	error.s blinken.s cache_def.s sram_test.s size_ram.s dram_test.s
HFILES = mytypes.h packer.h mfpic.h ns202.h dosdisk.h ide.h main68.h ctype.h \
  string.h coff.h myide.h rtc.h io.h fdc8272.h wd37c65.h debug.h diskio.h version.h
HSFILES = portab.h optab.h disasm.h
HFFILES = ff.h ffconf.h diskio.h integer.h
OFILES = main68.o serial.o rtc.o ds1302.o cprintf.o packer.o \
	pic202.o ns202.o ppide.o dualide.o bios8.o malloc.o string.o\
	dualsd.o bioscall.o fdc8272.o wd37c65.o floppy.o setup.o \
	debug.o beetle.o disasm.o ff.o prettydump.o diskio.o uart2.o \
	memtest3.o strtoul.o 
CSFILES = main68.s cprintf.s packer.s ns202.s crc32.s malloc.s setup.s \
	rtc.s string.s fdc8272.s wd37c65.s debug.s disasm.s \
	prettydump.s diskio.s ff.s strtoul.s # ppide2.s 



TESTS = test3.bin test4.bin test5.bin

TABLES = startup.sym startup.mod
TTABLES = test5.sym test5.mod daytime.sym daytime.mod

LIBFILES = cprintf.o bioscall.o crt0.o ff.o strtoul.o





all:	$(ALL)
	$(COPY)

test:	$(TESTS)          #     daytime.bin $(TTABLES)
	
rom:	all
	minipro -p $(FLASH) -w $(BURN)
burn:	rom


alles:	all test

#ide:	ppide2.o
dt:	daytime.out
fdc:	fdc8272.o wd37c65.o floppy.o
gccver:
	$(CC) -v
	
rw:
	chmod ug+w *.?

	

mini-512.rom:	$(ROM)/rom464.bin $(TARGET).bin
	cat $(TARGET).bin $(ROM)/rom464.bin >mini-512.rom

mini-128.rom:	$(ROM)/rom80.bin $(TARGET).bin
	cat $(TARGET).bin $(ROM)/rom80.bin >mini-128.rom

kiss-512.rom:	$(ROM)/krom464.bin $(TARGET).bin
	cat $(TARGET).bin $(ROM)/krom464.bin >kiss-512.rom

kiss-128.rom:	$(ROM)/krom80.bin $(TARGET).bin
	cat $(TARGET).bin $(ROM)/krom80.bin >kiss-128.rom
	
$(P)rom64.bin:	$(ROM)/$(P)rom80.bin
	$(BIN2HEX) -o $(P)rom80.hex $(ROM)/$(P)rom80.bin
	$(HEX2BIN) -o $(P)rom64.bin -D 64k $(P)rom80.hex

$(P)rom448.bin:	$(ROM)/$(P)rom464.bin
	$(BIN2HEX) -o $(P)rom464.hex $(ROM)/$(P)rom464.bin
	$(HEX2BIN) -o $(P)rom448.bin -R 448k -D 448k $(P)rom464.hex

$(P)test128.bin:	$(TARGET).bin $(P)rom64.bin
	cat $(TARGET).bin $(P)rom64.bin >$(P)test128.bin

$(P)test512.bin:	$(TARGET).bin $(P)rom448.bin
	cat $(TARGET).bin $(P)rom448.bin >$(P)test512.bin

main68.o:	main68.c $(HFILES)
	$(CC) -S $(COPT) -DBIOSSIZE=$(BIOSSIZE) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

cprintf.o:	cprintf.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

packer.o:	packer.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

crc32.o:	crc32.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

malloc.o:	malloc.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

diskio.o:	diskio.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

prettydump.o:	prettydump.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

fdc8272.o:	fdc8272.c fdc8272.h $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

wd37c65.o:	wd37c65.c wd37c65.h $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

#ppide2.o:	ppide2.c $(HFILES)
#	$(CC) -S $(COPT) $*.c
#	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

setup.o:	setup.c $(HFILES) stamp.h
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

rtc.o:	rtc.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

string.o:	string.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

ns202.o:	ns202.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

debug.o:	debug.c $(HFILES) $(HSFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

disasm.o:	disasm.c $(HFILES) $(HSFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

strtoul.o:	strtoul.c $(HFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

ff.o:	ff.c $(HFFILES)
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s
	
stamp.h:
	echo "\""`date`"\"" >stamp.h

stomp.h:
	echo "\""`date`"\"" >stomp.h


$(TARGET).out:	startup.o bios.a
	$(LD) $(LOPT) -s -Map $(TARGET).map -o $(TARGET).out startup.o \
		bios.a $(LIBS)

$(TARGET).hex:	$(TARGET).out
	$(BIN2HEX) -o $(TARGET).hex -s 0x2000 -D $(BIOSSIZE)k $(TARGET).out

$(TARGET).bin:	$(TARGET).hex		# $(TUTOR)
	$(HEX2BIN) -R $(BIOSSIZE)k $(TARGET).hex   -o $(TARGET).bin

mylib.a:   $(LIBFILES)
	$(LIB) -r $*.a $(LIBFILES)

bios.a:	   $(OFILES)
	$(LIB) -r $*.a $(OFILES)

$(TARGET).mod:	$(TARGET).out
	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
		grep -v "set to" | sed "s/.text/     /" > $*.mod

$(TARGET).sym:	$(TARGET).out
	grep "                " $*.map | grep -v "=" | grep -v "(" | \
		grep -v LONG | grep -v "                 " | sort > $*.sym


test1.out:	test1.o
	$(LD) $(LOPT) $(LIBS) -s -Map test1.map -o test1.out test1.o

test1.bin:	test1.out
	$(BIN2HEX) -s 0x2000 test1.out -o test1.hex
	$(HEX2BIN) -R 8k test1.hex -o test1.bin

test1.mod:	test1.out
	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
		grep -v "set to" | sed "s/.text/     /" > $*.mod

test1.sym:	test1.out
	grep "                " $*.map | grep -v "=" | grep -v "(" | \
		grep -v LONG | grep -v "                 " | sort > $*.sym



test2.out:	test2.o
	$(LD) $(LOPT) $(LIBS) -s -Map test2.map -o test2.out test2.o

test2.bin:	test2.out
	$(BIN2HEX) -s 0x2000 test2.out -o test2.hex
	$(HEX2BIN) -R 8k test2.hex -o test2.bin

test2.mod:	test2.out
	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
		grep -v "set to" | sed "s/.text/     /" > $*.mod

test2.sym:	test2.out
	grep "                " $*.map | grep -v "=" | grep -v "(" | \
		grep -v LONG | grep -v "                 " | sort > $*.sym


test3.out:	test3.o
	$(LD) $(LOPT) $(LIBS) -s -Map test3.map -o test3.out test3.o

test3.bin:	test3.out
	$(BIN2HEX) -s 0x2000 test3.out -o test3.hex
	$(HEX2BIN) -R 128k test3.hex -o test3.bin

test3.mod:	test3.out
	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
		grep -v "set to" | sed "s/.text/     /" > $*.mod

test3.sym:	test3.out
	grep "                " $*.map | grep -v "=" | grep -v "(" | \
		grep -v LONG | grep -v "                 " | sort > $*.sym


test4.o:	test3.s memtest2.s uart.s biostrap.s hardware.s
	$(AS) $(AOPT) --defsym SIZE=64 -a=$*.lst -o $*.o test3.s

test4.out:	test4.o
	$(LD) $(LOPT) $(LIBS) -s -Map test4.map -o test4.out test4.o

test4.bin:	test4.out
	$(BIN2HEX) -s 0x2000 test4.out -o test4.hex
	$(HEX2BIN) -R 128k test4.hex -o test4.bin

test4.mod:	test4.out
	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
		grep -v "set to" | sed "s/.text/     /" > $*.mod

test4.sym:	test4.out
	grep "                " $*.map | grep -v "=" | grep -v "(" | \
		grep -v LONG | grep -v "                 " | sort > $*.sym


test5.o:	test5.s memtest2.s uart.s biostrap.s hardware.s
	$(AS) $(AOPT) -a=$*.lst -o $*.o test5.s

test5.out:	test5.o
	$(LD) $(LOPT) $(LIBS) -s -Map test5.mapr -o test5.out test5.o

test5.elf:	test5.o
	$(LD) $(TOPT) $(LIBS) -s -Map test5.mape -o test5.elf test5.o

test5.bin:	test5.out
	$(BIN2HEX) -s 0x2000 test5.out -o test5.hex
	$(HEX2BIN) -R 128k test5.hex -o test5.bin

test5.mod:	test5.out
	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
		grep -v "set to" | sed "s/.text/     /" > $*.mod

test5.sym:	test5.out
	grep "                " $*.map | grep -v "=" | grep -v "(" | \
		grep -v LONG | grep -v "                 " | sort > $*.sym


#  cat $(TARGET).mod $(TARGET).sym | sed -e "s/        / /g" | sort >foo

daytime.o:	daytime.c bioscall.h
	$(CC) -S $(COPT) $*.c
	$(AS) $(AOPT) -a=$*.lst -o $*.o $*.s

daytime.out:	daytime.o mylib.a
	$(LD) $(UOPT) -s -Map daytime.map -o daytime.out \
		daytime.o mylib.a $(LIBS)
#	$(BIN2HEX) -s 0x1000 daytime.out -o daytime.hex
#	$(HEX2BIN) -R 8k daytime.hex -o daytime.bin

daytime.bin:	daytime.out
	$(BIN2HEX) -s 0x1000 daytime.out -o daytime.hex
	$(HEX2BIN) -R 8k daytime.hex -o daytime.bin

daytime.sym:	daytime.out
	grep "                " $*.map | grep -v "=" | grep -v "(" | \
		grep -v LONG | grep -v "                 " | sort > $*.sym

daytime.mod:	daytime.out
	grep ".text" $*.map | grep -v ".o)" | grep ".o" | \
		grep -v "set to" | sed "s/.text/     /" > $*.mod



tidy:	
	rm -f startup.out
	rm -f startup.mod
	rm -f startup.sym
	rm -f *.lst *.LST
#	rm -f *.map

clean:	tidy
	rm -f $(CSFILES)
	rm -f *.o
	rm -f *.a
	rm -f *.hex
	rm -f *.bin *.BIN
	rm -f *.out
	rm -f stamp.h

spotless:	clean
	rm -f stomp.h
	rm -f *.rom
	rm -f *.map
	

## Dependencies
startup.o:	startup.s $(SFILES)
serial.o:	serial.s  $(SFILES)
uart2.o:	uart2.s	$(SFILES)
dualide.o:	dualide.s $(SFILES)
ppide.o:	ppide.s $(SFILES)
dualsd.o:	dualsd.s $(SFILES)
pic202.o:	pic202.s $(SFILES)
bios8.o:	bios8.s $(SFILES)
bioscall.o:	bioscall.s $(SFILES)
test5.o:	test5.s biostrap.s
ds1302.o:	ds1302.s $(SFILES)
floppy.o:	floppy.s $(SFILES)
#memtest.o:	memtest.s $(SFILES)	Used on an 'include' in startup.s
memtest3.o:	memtest3.s

foo.o:		foo.c
time.o:		time.c $(HFILES)
crt0.o:		crt0.s

beetle.o:	beetle.s
n8iox.o:	n8iox.s



