#! /bin/sh
#
export ZSUF=tar.gz
export ZIP="tar cvfz"
export DRIVE=BULLET8-1
export DIR=M68K/BIOS10.3

echo "SAVE has control"   $1    $2    ..

if [ ! "$1" ]; then
	echo listing ...
	ls -ltr --color=always *.$ZSUF
	echo end of list
	exit
fi
if [ -e "$1" ]; then
	echo "\"$1\"" already exists
	exit
fi
if [ -e "$1.$ZSUF" ]; then
	echo \"$1.$ZSUF\" already exists
	exit
fi

$ZIP $1.$ZSUF COPYING notice save ?akefil* *.s* *.c* *.h* *.b* *.a* *.txt *.ld *.rom # *.hex *.doc *.pdf
echo Done Compression.

cp -v $1.$ZSUF /media/jrc/$DRIVE/$DIR

echo Done Save.
exit
